config/routes.rb
Rails.application.routes.draw do
  root "pages#main"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: "registrations" }

  resources :spots do
    resources :ratings
  end

  get "/users",           to: "pages#main"
  get "/users/:id",       to: "pages#user_profile"
  get "/users/password",  to: redirect("/users/password/new")

  get "/map",             to: "pages#map"
  get "/api/spots",       to: "spots#api_index"
  get "/api/spots/:id",   to: "spots#api_show"

  namespace :admin do
    resources :users
  end
  post "sign_out_all/action", to: "admin/users#sign_out_all"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/spot.rb
class Spot < ApplicationRecord
  has_many :ratings, dependent: :destroy, foreign_key: :spot_id
  belongs_to :user

  def average_rating
    ratings.blank? ? 0 : (ratings.sum(:score).to_f / ratings.count).round(1)
  end

  # validations
  validates_presence_of :name,
                        :user_id,
                        :spot_type,
                        :description,
                        :latitude,
                        :longitude
  validates :spot_type, inclusion: {
    in: %w[free_spot paid_spot campsite mtb_spot climbing_spot kayaking_spot surf_spot bad_spot],
    message: "%{value} is not a valid spot type" }
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :api_index, :api_show ]
  before_action :set_spot, only: [ :show, :api_show, :update, :destroy ]
  before_action :require_permission, only: [ :edit, :update, :destroy ]

  # GET /spots
  def index
    # TODO: Add Pagination
    @spots =
      if params[:spot_type]
        Spot.where(spot_type: params[:spot_type])
      else
        Spot.includes(:user, :ratings).all.sort_by(&:average_rating).reverse
      end
  end

  # GET /api/spots
  def api_index
    if params[:spot_type]
      @spots = Spot.where(spot_type: params[:spot_type])
    else
      @spots = Spot.all.includes(:user, :ratings)
    end
    render json: @spots.as_json(methods: [ :average_rating ])
  end

  # GET /spots/:id
  def show
    @spot
  end

  # GET /api/spots/:id
  def api_show
    @spot
    render json: @spot.as_json(methods: [ :average_rating ])
  end

  # GET /spots/new
  def new
    @spot = Spot.new
    if params["latitude"].present? && params["longitude"].present?
      @spot.latitude = params["latitude"]
      @spot.longitude = params["longitude"]
    end
  end

  # POST /spots
  def create
    if (@spot = current_user.spots.create!(spot_params))
      redirect_to @spot
    else
      render "new"
    end
  end

  # GET /spots/:id/edit
  def edit
    @spot = Spot.find(params[:id])
  end

  # PUT /spots/:id
  def update
    @spot = Spot.find(params[:id])

    if @spot.update(spot_params)
      redirect_to @spot
    else
      render "edit"
    end
  end

  # DELETE /spots/:id
  def destroy
    @spot.destroy
    redirect_to spots_path
  end

  private

  def require_permission
    unless current_user == Spot.find(params[:id]).user || current_user.admin?
      redirect_to spot_path
    end
  end

  def spot_params
    # whitelist params
    params.require(:spot).permit(:name, :spot_type, :description, :latitude, :longitude, :web_link)
  end

  def set_spot
    @spot = Spot.find(params[:id])
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_card.html.erb
<div class="card spot-card <%= spot.spot_type %> rating-<%= spot.average_rating.floor %>">
  <div class="card-header text-center" >
    <% if user_signed_in? %>
      <a href="/spots/<%= spot.id %>">
    <% end %>

    <h2 class="card-title"><%= spot.name %></h2>
    <h5><%= spot.spot_type.humanize %> - <%= spot.average_rating %>/10</h5>

    <% if user_signed_in? %>
      </a>
    <% end %>
  </div>

  <div class="card-body">
    <h6>Created By: <% if user_signed_in? %><a href="/users/<%= spot.user.id %>"> <% end %><%= spot.user.username %><% if user_signed_in? %></a><% end %> on <%= spot.created_at.strftime('%b %d, %Y') %></h6>
    <%= spot.description %>
  </div>

  <div class="more-info">
    <div class="card-footer text-center">
      <% if user_signed_in? %>
        <%= link_to "More Info", spot_path(spot) %>
      <% else %>
        <%= link_to new_user_session_path, :class => 'nav-link' do%>
          Login for More Info
        <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/spots/edit.html.erb
<%= render partial: 'layouts/alerts' %>
<div class="vs-form">
  <h2>Edit <em><%= @spot.name %></em></h2>

  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@spot.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @spot.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @spot, url: {action: "update"} do |spot_form| %>
    <div class="form-group floating-label">
      <%= spot_form.text_field :name, class: 'form-control', :required => true, :placeholder => 'What do you call this spot?'  %>
      <%= spot_form.label :name, 'Spot Name' %>
    </div>

    <div class="form-group select-div">

      <%= spot_form.select(:spot_type,
                           options_for_select([['Free Spot', 'free_spot'],
                                               ['Paid Spot', 'paid_spot'],
                                               ['Campsite', 'campsite'],
                                               ['MTB Spot', 'mtb_spot'],
                                               ['Climbing Spot', 'climbing_spot'],
                                               ['Kayaking Spot', 'kayaking_spot'],
                                               ['Surf Spot','surf_spot'],
                                               ['Bad Spot', 'bad_spot']
                                              ], @spot.spot_type),
                           {include_blank: false,
                            include_hidden: false},
                           {:class => 'form-control'}) %>
      <%= spot_form.label :spot_type, 'Spot Type' %>
    </div>
    <div class="form-group floating-label">
      <%= spot_form.text_area :description, class: 'form-control', :required => true, :placeholder => 'Tell us a bit about this spot. Does it have good views? It is free after a certain time? How many spots are there?'  %>
      <%= spot_form.label :description %>
    </div>

    <!--    <%#= spot_form.label :location %><br />-->
    <div class="form-row">
      <div class="form-group col-sm-6  floating-label">
        <%= spot_form.text_field :latitude,
                                 class: 'form-control',
                                 :required => true,
                                 :pattern => "^(\\+|-)?(?:90(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,16})?))$",
                                 :placeholder => 'Latitude E.g. 51.605411'
        %>
        <%= spot_form.label :latitude, ' Location - Latitude' %>
      </div>
      <div class="form-group col-sm-6  floating-label">

        <%= spot_form.text_field :longitude,
                                 class: 'form-control',
                                 :required => true,
                                 :pattern => "^(\\+|-)?(?:180(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,16})?))$",
                                 :placeholder => 'Longitude E.g. -3.983570'
        %>
        <%= spot_form.label :longitude, ' Location - Longitude' %>
      </div>
    </div>

    <div class="form-group floating-label">
      <%= spot_form.url_field :web_link, class: 'form-control', :required => false, :placeholder => 'External link for more information'  %>
      <%= spot_form.label :web_link, 'External Link' %>
    </div>

    <div class="actions form-group">
      <%= link_to "Back", :back, class: 'btn btn-secondary' %>
      <%= spot_form.submit "Update Spot", class: 'btn btn-primary'  %>
    </div>

  <% end %>

</div>

app/views/spots/index.html.erb
<div class="table-index">
  <div class="content" data-controller="card-filter">
    <div class="content-header">
      <h1> <span class="headingBrandVan">Van</span> <span class="headingBrandSpots">Spots</span> </h1>
      <% if user_signed_in? %>
        <%= link_to "Create Spot", new_spot_path, class: 'btn btn-sm btn-primary' %>
      <% end %>
      <hr />
    </div>

    <div class="filter-buttons" id="type-filters">
      <button class="btn btn-sm active" data-action="click->card-filter#filterByType" data-spot-type="all">Show All</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByType" data-spot-type="free_spot">Free Spots</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByType" data-spot-type="paid_spot">Paid Spots</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByType" data-spot-type="mtb_spot">MTB Spots</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByType" data-spot-type="climbing_spot">Climbing Spots</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByType" data-spot-type="kayaking_spot">Kayaking Spots</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByType" data-spot-type="surf_spot">Surf Spots</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByType" data-spot-type="bad_spot">Bad Spots</button>
    </div>
    <div class="filter-buttons" id="rating-filters">
      <button class="btn btn-sm active" data-action="click->card-filter#filterByRating" data-rating="all">All</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByRating" data-rating="5">>5/10</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByRating" data-rating="6">>6/10</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByRating" data-rating="7">>7/10</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByRating" data-rating="8">>8/10</button>
      <button class="btn btn-sm" data-action="click->card-filter#filterByRating" data-rating="9">>9/10</button>
    </div>

    <% unless user_signed_in? %>
      <div class="col-xl-4 col-lg-5 col-md-6 col-sm-7 mx-auto text-center sign-in-error alert alert-danger"><a href="users/sign_in" class="alert-link">Login</a> or <a href="users/sign_up" class="alert-link">Sign up</a> to see detail about each spot.</div>
    <% end %>
      <div id="spot-table" data-card-filter-target="spotTable" class="table-responsive">
        <div class="text-center loading-icon" data-card-filter-target="loadingIcon"><h3>Loading</h3><i class="far fa-compass fa-2x fa-spin"></i></div>
        <table class="table table-dark table-hover table-sm">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Type</th>
              <th scope="col">Rating</th>
              <th scope="col"></th>
              <th scope="col">Description</th>
              <th scope="col">Created By</th>
              <th scope="col">Created At</th>
              <th scope="col">Last Update</th>
            </tr>
          </thead>
          <tbody>
            <% @spots.each do |spot| %>
            <%# I apologise sincerely for anyone else who has to read the following line of code%>
              <tr class="<%= spot.spot_type %> rating-<%= spot.average_rating.floor %> hide
              <% if user_signed_in? %>clickable" onclick="window.location='/spots/<%= spot.id %>';<% end %>"
                data-rating="<%= spot.average_rating.floor %>"
                data-card-filter-target="filterable">

                <td><%= spot.name %></td>
                <td><% spot.spot_type.humanize  %></td>
                <td><%= spot.average_rating %>/10</td>
                <td>from <%= spot.ratings.size %> scores</td>
                <td><%= spot.description.truncate(60) %></td>
                <td><%= spot.user.username %></td>
                <td><%= spot.created_at.strftime('%b %d, %Y') %></td>
                <td><%= spot.updated_at.strftime('%b %d, %Y') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
     </div> <!-- #spot-table -->
    <div id="no-spots-error" data-card-filter-target="noSpotsError" class="no-spots-error alert alert-danger text-center">
      <h3> Sorry, no spots found. Try browsing the <a href="/map" class="alert-link">map</a></h3>
    </div>

  </div>
</div>

app/views/spots/new.html.erb
<%= render partial: 'layouts/alerts' %>
<div class="vs-form">
  <h2>Create New Spot</h2>

  <%= form_for @spot, url: {action: "create"} do |spot_form| %>
    <div class="form-group floating-label">
      <%= spot_form.text_field :name, class: 'form-control', :required => true, :placeholder => 'What do you call this spot?'  %>
      <%= spot_form.label :name, 'Spot Name' %>
    </div>

    <div class="form-group select-div">

      <%= spot_form.select(:spot_type,
                           options_for_select([['Free Spot', 'free_spot'],
                                               ['Paid Spot', 'paid_spot'],
                                               ['Campsite', 'campsite'],
                                               ['MTB Spot', 'mtb_spot'],
                                               ['Climbing Spot', 'climbing_spot'],
                                               ['Kayaking Spot', 'kayaking_spot'],
                                               ['Surf Spot','surf_spot'],
                                               ['Bad Spot', 'bad_spot']
                                              ]),
                           {include_blank: false,
                            include_hidden: false},
                           {:class => 'form-control', :selected => 'Free Spot'}) %>
      <%= spot_form.label :spot_type, 'Spot Type' %>
    </div>

    <div class="form-group floating-label">
      <%= spot_form.text_area :description, class: 'form-control', :required => true, :placeholder => 'Tell us a bit about this spot. Does it have good views? It is free after a certain time? How many spots are there?'  %>
      <%= spot_form.label :description %>
    </div>

<!--    <%#= spot_form.label :location %><br />-->
    <div class="form-row">
      <div class="form-group col-sm-6  floating-label">
        <%= spot_form.text_field :latitude,
                                 class: 'form-control',
                                 :required => true,
                                 :pattern => "^(\\+|-)?(?:90(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\\.[0-9]{1,16})?))$",
                                 :placeholder => 'Latitude E.g. 51.605411'
        %>
        <%= spot_form.label :latitude, ' Location - Latitude' %>
      </div>
      <div class="form-group col-sm-6  floating-label">

        <%= spot_form.text_field :longitude,
                                 class: 'form-control',
                                 :required => true,
                                 :pattern => "^(\\+|-)?(?:180(?:(?:\\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\\.[0-9]{1,16})?))$",
                                 :placeholder => 'Longitude E.g. -3.983570'
        %>
        <%= spot_form.label :longitude, ' Location - Longitude' %>
      </div>
    </div>

    <div class="form-group floating-label">
      <%= spot_form.url_field :web_link, class: 'form-control', :required => false, :placeholder => 'External link for more information'  %>
      <%= spot_form.label :web_link, 'External Link' %>
    </div>

    <div class="actions form-group">
      <%= link_to "Back", :back, class: 'btn btn-secondary' %>
      <%= spot_form.submit "Create Spot", class: 'btn btn-primary'  %>
    </div>

  <% end %>

</div>

app/views/spots/show.html.erb
<% content_for :head do %>
  <script>
      (g => {
          var h, a, k, p = "The Google Maps JavaScript API", c = "google", l = "importLibrary", q = "__ib__", m = document, b = window;
          b = b[c] || (b[c] = {});
          var d = b.maps || (b.maps = {}), r = new Set, e = new URLSearchParams, u = () => h || (h = new Promise(async (f, n) => {
              await (a = m.createElement("script"));
              e.set("libraries", [...r] + "");
              for (k in g) e.set(k.replace(/[A-Z]/g, t => "_" + t[0].toLowerCase()), g[k]);
              e.set("callback", c + ".maps." + q);
              a.src = `https://maps.${c}apis.com/maps/api/js?` + e;
              d[q] = f;
              a.onerror = () => h = n(Error(p + " could not load."));
              a.nonce = m.querySelector("script[nonce]")?.nonce || "";
              m.head.append(a)
          }));
          d[l] ? console.warn(p + " only loads once. Ignoring:", g) : d[l] = (f, ...n) => r.add(f) && u().then(() => d[l](f, ...n))
      })({
          key: "<%= ENV['MAPS_API_KEY'] %>",
          v: "weekly",
          // Use the 'v' parameter to indicate the version to use (weekly, beta, alpha, etc.).
          // Add other bootstrap parameters as needed, using camel case.
      });
  </script>
<% end %>

<div id="page-top" class="show-spot">
  <div class="spot-header text-center <%= @spot.spot_type %>">
    <%= render partial: 'layouts/alerts' %>
    <h1><%= @spot.name %></h1>
    <h6>
      <small>Created By</small> <a href="/users/<%= @spot.user.id %>"> <%= @spot.user.username %> </a>
      <small>on</small> <%= @spot.created_at.strftime('%b %d, %Y') %>
    </h6>
    <h6>Score: <%= @spot.average_rating %>/10</h6>
    <% if @spot.web_link.present? %>
      <h6><%= link_to 'External Info', @spot.web_link %></h6>
    <% end %>
    <h6>
      <%= link_to 'Directions', 'https://www.google.com/maps/dir/?api=1&destination=' +
        @spot.latitude.to_s + ',' + @spot.longitude.to_s, target: :_blank, class: 'btn btn-sm btn-secondary' %>
    </h6>

    <h6>Type: <strong>
      <% @spot.spot_type.humanize %></strong></h6>

    <!--Edit if Owner or Admin-->
    <!-- Rate Spot button-->
    <div class="button-group text-center">
      <% if current_user.id == @spot.user_id || current_user.admin? %>
        <%= link_to "Edit Spot", edit_spot_url(@spot), method: :get, class: 'btn btn-sm btn-primary' %>
      <% end %>
      <%= link_to "Rate Spot", new_spot_rating_path(@spot), class: 'btn btn-sm btn-primary' %>
    </div>
    <% if @spot.ratings.map(&:review_title).any?(&:present?) || @spot.ratings.map(&:review_body).any?(&:present?) %>
      <div class="button group text-center">
        <!--<a href="#map-title" class="btn btn-sm btn-info">Go to Map</a>-->
        <a href="#spot-reviews" class="btn btn-sm btn-info">Go to Reviews</a>
      </div>
    <% end %>

    <div class="col-md-8 mx-auto">
      <%= @spot.description %>
    </div>

    <!--Map Title-->
    <div class="ninety-container">
      <h3 id="map-title" class="text-center">Map
        <a href="#page-top" title="Page Top" class="float-right">
          <i class="fas fa-angle-double-up"></i>
        </a>
      </h3>
    </div>
  </div> <!--End of .spot-header-->

  <!--Map Div-->
  <div id="map" class="spot-map" data-controller="map" data-map-target="map"
       data-map-spot="<%= @spot.to_json %>"
       data-map-icons='{
       "free_spot": "<%= image_url('map-marker-purple.png') %>",
       "paid_spot": "<%= image_url('map-marker-orange.png') %>",
       "campsite": "<%= image_url('map-marker-darker-orange.png') %>",
       "mtb_spot": "<%= image_url('map-marker-darker-green.png') %>",
       "climbing_spot": "<%= image_url('map-marker-green.png') %>",
       "kayaking_spot": "<%= image_url('map-marker-darker-blue.png') %>",
       "surf_spot": "<%= image_url('map-marker-sky-blue.png') %>",
       "bad_spot": "<%= image_url('map-marker-red.png') %>",
       "user": "<%= image_url('map-marker-ink.png') %>",
       "new": "<%= image_url('map-marker-lighter-ink.png') %>"
     }'></div>

  <!--Reviews-->
  <div id="spot-reviews" class="ninety-container">
    <% if @spot.ratings.map(&:review_title).any?(&:present?) || @spot.ratings.map(&:review_body).any?(&:present?) %>
      <h3 class="text-center">Reviews
        <a href="#page-top" title="Page Top" class="float-right">
          <i class="fas fa-angle-double-up"></i>
        </a>
      </h3>
      <div class="card-columns">
        <% @spot.ratings.reverse.each do |rating| %>
          <% next unless rating.review_title? %>
          <%= render partial: 'ratings/card', locals: { rating: } %>
        <% end %>
      </div>
    <% else %>
      <h4 class="text-center">No reviews for this spot.</h4>
    <% end %>
  </div>

  <!--Spot Stats-->
  <div class="container text-center">
    <h3>Stats </h3>
    Total Score: <%= @spot.ratings.map(&:score).sum %> <br/>
    Total Ratings: <%= @spot.ratings.count %><br/>
    Total Reviews: <%= @spot.ratings.map(&:review_title).count(&:present?) %>
  </div>

</div> <!-- End Content .show-spot -->