config/routes.rb
Rails.application.routes.draw do
  root "pages#main"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: "registrations" }

  resources :spots do
    resources :ratings
  end

  get "/users",           to: "pages#main"
  get "/users/:id",       to: "pages#user_profile"
  get "/users/password",  to: redirect("/users/password/new")

  get "/map",             to: "pages#map"
  get "/api/spots",       to: "spots#api_index"
  get "/api/spots/:id",   to: "spots#api_show"

  namespace :admin do
    resources :users
  end
  post "sign_out_all/action", to: "admin/users#sign_out_all"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  validates_presence_of :user_id, :spot_id, :score
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_spot # , except: :ratings_index
  before_action :set_spot_rating, only: [ :update, :destroy ]
  before_action :require_permission, only: [ :edit, :update, :destroy ]

  # GET /spots/new
  def new
    @rating = Rating.new
  end

  # POST /spots/:spot_id/ratings
  def create
    if current_user.ratings.create!(rating_params)
      redirect_to @spot
    else
      render "edit"
    end
  end

  # GET /spots/:id/ratings/:id/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # PUT /spots/:spot_id/ratings/:id
  def update
    @rating = Rating.find(params[:id])

    if @rating.update(rating_params)
      redirect_to @spot
    else
      render "edit"
    end
  end

  # DELETE /spots/:spot_id/ratings/:id
  def destroy
    @rating.destroy

    redirect_to @spot
  end

  private

  def require_permission
    if current_user != Rating.find(params[:id]).user
      redirect_to spot_path
    end
  end

  def rating_params
    params.require(:rating).permit(:score, :review_title, :review_body, :spot_id)
  end

  def set_spot
    @spot = Spot.find(params[:spot_id])
  end

  def set_spot_rating
    @rating = @spot.ratings.find_by!(id: params[:id]) if @spot
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_card.html.erb
<div class="card
              <% if rating.score < 3 %>border-danger
              <% elsif rating.score < 6 %>border-warning
              <% elsif rating.score < 8 %>border-info
              <% else %>border-success
              <% end %>">

  <div class="card-header text-center
                <% if rating.score < 3 %>border-danger bg-danger-subtle
                <% elsif rating.score < 6 %>border-warning bg-warning-subtle
                <% elsif rating.score < 8 %>border-info bg-info-subtle
                <% else %>border-success bg-success-subtle
                <% end %>">
    <h3> <%= rating.score %>/10</h3>
    <h5>
      <% if user_signed_in? %><a href="/spots/<%= rating.spot.id %>">
      <% end %><%= rating.spot.name %>
      <% if user_signed_in? %></a>
      <% end %></h5>
  </div>

  <div class="card-body">
    <h4 class="card-title text-center"><%= rating.review_title %></h4>
    <p class="card-text text-justify"><%= rating.review_body&.truncate(170) %></p>
  </div>

  <div class="card-footer">
    <small class="text-muted">by <a href="/users/<%= rating.user.id %>"><%= rating.user.username %></a>
      on <%= rating.created_at.strftime('%b %d, %Y') %></small>
  </div>

  <%# if current_user.id == rating.user_id%>
  <!--                      <div class="text-center">-->
  <%#= button_to "Edit Review", edit_spot_rating_url(@spot, rating), method: :get, class: 'btn btn-primary' %>
  <!-- TODO add delete option -->
  <!--                      </div>-->
  <%# end %>
</div>

app/views/ratings/edit.html.erb
<%= render partial: 'layouts/alerts' %>
<div class="vs-form">
  <h2>Edit your rating for:</h2>
  <h2><%= @spot.name %>?</h2>
  <div>
    <%= @spot.description %>
  </div>

  <br/>

  <%= form_for @rating, url: {action: "update"} do |rating_form| %>
    <div class="form-group">
      <%= rating_form.label :score %><br/>
      <%= rating_form.text_field :score, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= rating_form.label :review_title, 'Review Title' %><br/>
      <%= rating_form.text_field :review_title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= rating_form.label :review_body, 'Review Body' %><br/>
      <%= rating_form.text_area :review_body, class: 'form-control' %>
    </div>

    <div class="actions form-group">
      <%= link_to "Back", :back, class: 'btn btn-secondary' %>
      <%= rating_form.submit "Update Rating", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/ratings/new.html.erb
<%= render partial: 'layouts/alerts' %>
<!--jquery bar ratings-->
<!--<script type="text/javascript">-->
<!--    $(function() {-->
<!--        $('#rating_score').barrating({-->
<!--            theme: 'bars-pill',-->
<!--            showValues: true,-->
<!--            showSelectedRating: false-->
<!--        });-->
<!--    });-->
<!--</script>-->

<div class="vs-form" data-controller="bar-rating" data-bar-rating-show-values="true" data-bar-rating-show-selected-rating="false">
  <h2>How would you rate:</h2>
  <h2><%= @spot.name %>?</h2>
  <div>
    <%= @spot.description %>
  </div>

  <br/>

  <%= form_for @rating, url: {action: "create"} do |rating_form| %>
    <div class="form-group">
      <%= rating_form.label :score %>
      <%= rating_form.select(:score,
                             options_for_select((1..10).step(1),5),
                             {include_blank: false,
                              include_hidden: false},
                             {class: 'form-control', data: {bar_rating_target: 'select'}}) %>

    </div>

    <div class="form-group floating-label">
      <%= rating_form.text_field :review_title, class: 'form-control', placeholder: 'Review Title (Optional)' %>
      <%= rating_form.label :review_title %>
    </div>

    <div class="form-group floating-label">
      <%= rating_form.text_area :review_body, class: 'form-control', placeholder: 'Review Body (Optional)' %>
      <%= rating_form.label :review_body %>
    </div>

    <%= rating_form.hidden_field :spot_id, value: @spot.id %>

    <div class="actions form-group">
      <%= link_to "Back", :back, class: 'btn btn-secondary' %>
      <%= rating_form.submit "Rate Spot", class: 'btn btn-primary' %>
    </div>

  <% end %>
</div>